[pyprland]
plugins = ["scratchpads", "magnify"]

[scratchpads.bluetooth]
command = "overskride"
animation = "fromRight"
margin = 20
lazy = true

[scratchpads.wifi]
command = "iwgtk"
animation = "fromRight"
margin = 20
lazy = true
